M48
; DRILL file {KiCad (6.0.1)} date Tue Feb 22 13:56:28 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-22T13:56:28+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X7.6976Y-3.8862
X7.6976Y-4.1138
T2
X2.5Y-1.8
X2.5Y-3.6
X6.95Y-1.8
X6.95Y-3.6
T0
M30
